// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:0394244a-bfa0-443e-90cc-da441e47a991",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_EYrlbn1k2",
    "aws_user_pools_web_client_id": "2c3688amvsm6825t9jd3subl6n"
};


export default awsmobile;
